### DISCUSSION TITLE
Gradle source not supported?

### DISCUSSION THREAD

**Discussion by perstrom** [rhyskoedijk/sbom-azure-devops#100] [Q&A]
Hi. To start off, thanks for a great extension! It generates a real nice and valuable sorted output for SBOM/CVE/License etc. However I cannot get it to work with Gradle/Java sources. The sbom tool itself expects a .lockfile in the Gradle source code (-bc) to be able to read the packages. This .lockfile is present in the source and when using sbom tool manually it identifies it and can generate a list of packages. However, when using the same arguments with the extension it does seem to identify the .lockfile and 0 packages are found. I have tried using different build artifacts types (-b) like .jar .zip Docker but no difference.

sbom-tool (Identifies .lockfile):
`$(Agent.TempDirectory)/sbom-tool generate -b $(Build.ArtifactStagingDirectory) -bc $(Build.SourcesDirectory) -pn $(productID) -pv $(packageVersion) -ps $(companyName) -nsb https://url.com -V Verbose`

sbom-tool extension (does not identify .lockfile):
```yaml
  - task: sbom-tool@1
    inputs:
      command: 'generate'
      buildSourcePath: '$(Build.SourcesDirectory)'
      buildArtifactPath: '$(Build.ArtifactStagingDirectory)'
      buildDockerImagesToScan: '' #'eclipse-temurin:21-jre-jammy'
      enableManifestSpreadsheetGeneration: true
      enableManifestGraphGeneration: true
      enablePackageMetadataParsing: true
      fetchLicenseInformation: true
      fetchSecurityAdvisories: true
      gitHubConnection: 'xxx'
      manifestOutputPath: '$(Build.ArtifactStagingDirectory)/SBOM'
      packageSupplier: '$(companyName)'
      packageName: '$(productID)'
      packageVersion: '$(packageVersion)'
```

Any ideas how to get it to work with .lockfiles? Thanks in advance!
